### PR TITLE
Improve code base; add build script, error handling and tests

### PR DESCRIPTION
**Pull request by sogreatandpowerfull**
Here are the changes I made:

* Declared variables `host` and `port` before reading them from user input. This is a good practice to avoid declaring variables in the middle of the code.

* *Added error handling*: In the original code, there was no error handling for the user input or the port scan. Used `Scanln` function to read user input and checked for any errors that may occur while reading. This is important because `Scanln` function can return an error if the input is not in the expected format.

* Used `Scanln` function to read user input and checked for any errors that may occur while reading. This is important because `Scanln` function can return an error if the input is not in the expected format.

* Used the `defer` keyword to close the connection after the main function has completed. This ensures that the connection is always closed, even if an error occurs during the execution of the main function.

* *Made the code more readable*: I added some comments to the code to make it more readable and easier to understand. I also refactored some of the code to make it more concise and easier to follow.

* Added a build script (build.sh) to the project to make it easier to compile the code. It can optimize the compiled binary for production or development builds.

* *Moved the port scanner code to a separate function*: In the original code, the port scanner code was contained within the `main` function. I moved this code to a separate function called `ScanPort`, which takes a host and port as arguments and returns a boolean value indicating whether the port is open or closed, as well as an error if one occurred during the scan.

* Added tests to the project to ensure that the code is functioning correctly and to provide a way to catch regressions in the future. The tests are located in the (portscanner_test.go) file, and they cover the main functionality of the `portscanner` package.

There are a few benefits to separating the port scanner code from the main function into a separate file:

- **Modularity**: By separating the code into a separate file, you can more easily reuse the port scanner code in other parts of your project or in other projects. You can also more easily test and debug the port scanner code by calling it directly from a separate test file.

- **Readability**: Splitting the code into separate files can make the code easier to read and understand, especially if the project is large and complex. By separating the main function from the port scanner code, you can more clearly see the high-level logic of the program and the specific details of the port scanner code.

- **Maintainability**: Separating the code into separate files can make it easier to maintain and update the code over time. For example, if you need to make changes to the port scanner code, you can do so in the portscanner.go file without affecting the main function in main.go. This can make it easier to manage and track changes to the codebase.

Tests are important for a number of reasons:

- Tests help to verify that the code is working as intended, and they provide a way to catch and fix bugs early in the development process.
- Tests serve as documentation for the code, helping to clarify the intended behavior and use cases for the various functions and types.
- Tests make it easier to refactor the code with confidence, knowing that the changes won't break existing functionality.

Signed-off-by: SoGreatAndPowerful <sogreatandpowerful@tuta.io>

### CODE REVIEW

**Comment by sogreatandpowerfull** [comment]
Hi, @sogo747! I would appreciate if you could take a look at the changes and let me know if you have any questions or suggestions for further improvements. I'm looking forward to your feedback!

**Comment by sogreatandpowerfull** [comment]
Hi, @sogo747! I would appreciate if you could take a look at the changes and let me know if you have any questions or suggestions for further improvements. I'm looking forward to your feedback!

**Comment by sogreatandpowerfull** [comment]
Hi, @sogo747! I would appreciate if you could take a look at the changes and let me know if you have any questions or suggestions for further improvements. I'm looking forward to your feedback!

**Comment by sogreatandpowerfull** [comment]
Hi, @sogo747! I would appreciate if you could take a look at the [changes](https://github.com/sogo747/nRAT/pull/1/files) and let me know if you have any questions or suggestions for further improvements. I'm looking forward to your feedback!

**Comment by sogreatandpowerfull** [comment]
Adding CI could be very beneficial for the project, as it would help to ensure that the code is working as intended and catch any regressions early. I recommend using a service such as [Travis CI](https://travis-ci.org/), [Jenkins](https://jenkins.io/) or [CircleCI](https://circleci.com/) to run the tests, and I would be happy to help set this up if needed. We could also use a code coverage service, such as [Codecov](https://codecov.io/), to track the test coverage of the project.

CI is important for a number of reasons:

- Helps to ensure that the code is working as intended, and it provides a way to catch and fix bugs early in the development process.
- Helps to enforce good coding practices and standards, such as running tests and linting tools.
- Makes it easier to integrate and deploy changes to the codebase, as it can automatically run tests and build the project when changes are pushed to the repository.

**Comment by sogo747** [comment]
Love the changes, thanks! Approved ✅.

**Pull request merged**
